apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: "-prod${namesuffix}"
commonLabels:
  app: "homepage-prod${namesuffix}"
  env: "prod"
resources:
- ../base
patch:
- path: virtualservice.yaml
  target:
    group: networking.istio.io
    version: v1beta1
    kind: VirtualService
