apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: config-homepage
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: "${envname}-homepage-config"
    kind: SecretStore
  target:
    name: "${envname}-config-homepage"
    deletionPolicy: "Delete"
  data:
  - secretKey: base.yaml
    remoteRef:
      key: tenants/t-pauwels-labs-main/configs/base/homepage/config
      property: config.yaml
  - secretKey: "${envname}.yaml"
    remoteRef:
      key: tenants/t-pauwels-labs-main/configs/${envname}/homepage/config
      property: config.yaml
