apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: config-homepage
spec:
  provider:
    vault:
      server: "${vaulturl}"
      path: "secrets"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "${clustername}"
          role: "tenant-configs-${environmentoverride:=${environment}}-reader"
          serviceAccountRef:
            name: "homepage"
