apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: homepage-config
spec:
  provider:
    vault:
      server: "http://vault.vault:8200"
      path: "secrets"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "repositories-config-reader"
          serviceAccountRef:
            name: "homepage"
