apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: "${envname}-homepage-config"
spec:
  provider:
    vault:
      server: "${vaulturl}"
      path: "secrets"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "${clustername}"
          role: "tenant-configs-${envname}-reader"
          serviceAccountRef:
            name: "${envname}-homepage"
