apiVersion: v1
kind: Service
metadata:
  name: homepage
  labels:
    toolkit.fluxcd.io/tenant: pauwels-labs-main
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv6
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: homepage
  type: ClusterIP
